### ISSUE TITLE
EXIF extraction (1)

### ISSUE THREAD

**Issue by Pino-Lupin** [ggoffy/wggallery#20]
Exif data are a lot ... In reality we need only to extract and publish only a small part that is listed here:
- Shot datetime
- Camera model
- Lens type
- Exposure time
- Aperture
- Focal length
- ISO

Obviously together with the dimensional characteristics of the JPG image; if a user wants to add other news, he has the comment attached to the photo, at the time of upload.

Very nice is the solution I saw in extGallery where this data remains hidden and appears only by clicking the gif "i" of Info ...

if you are going to create a choice option of the exif data to show (some do) MUST ONLY be inserted on the administration side

**Comment by ggoffy** [comment]
hi

please read https://www.php.net/manual/en/function.exif-read-data.php

you will realise that a few of the information are more or less standardize. others are depending on the camery model.
you wrote that you need only a few. this means that i have to make in preference a list for selection which one someone (else) want to see or not.

at the moment i have no idea how to treat this topic. the only option I see is show exif or show it not.

what do you mean?

**Comment by Pino-Lupin** [comment]
Ok, some points to clarify :

- I know you can't store a large amount of ( useless furthermore ) features ... when you memorize the top 5 or 6, you have already done a lot for standard uses.
- this is my SPECIFIC request: I am able to set up a database to receive more data, but I need to "intervene" in the data extraction section of the module, to "tell" it which data I want to store ... so, it would be great if there was some string to use in module administration section for this purpose (I think I saw something like that in extgallery), or, alternatively, a small "hack" to work on by myself ...

I hope I was clear enough, with my school English :-)

Cya soon

Pino "Lupin"

P.S. The other requests I put you in Ghithub, I think can be useful to everyone ...

**Comment by ggoffy** [comment]
hi Pino

I think it is not a problem to store the data. I will store all and then the user can decide want he want to see or not.

as there is no standard for exif and each camera producer/model use maybe different parameters I need as much as possible different examples.

can you please 
- download current version from github
- then upload images, if possible from different camera models
- send me the full exif data

**Comment by Pino-Lupin** [comment]
Hi goffy ,

I am not able to add tables here and I need to do it ... where i can send you a mail ? You know mine? If not, contact me by PM in xoops website ... ty

Pino

**Comment by ggoffy** [comment]
implemented in version 1.12
