### ISSUE TITLE
Images comments (2)

### ISSUE THREAD

**Issue by Pino-Lupin** [ggoffy/wggallery#21]
Of course , after images, their comments are important.

We need 3 levels of publication images : thumbs , medium  and original. 
Full comments will only be shown in the medium version ; on thumbs there will be only numerical infos ... it means , in this case : "number of comments = XX"
Original image must be shown in "_blank" call and doesn't need any info ( if you want only image name and user owner )
Since there will be a forum where add long discussions, I think could be useful a "chars limit" for comments , possibly adjustable in administration side.

Since comments may require a lot of space, it will be necessary that all other information of the image in the media version (votes, likes, owner's information, etc.) will be inserted BEFORE the comments.

**Comment by ggoffy** [comment]
implemented in version 1.12

number of comments shown on image index page

detailed comments on single image page
