### ISSUE TITLE
Categories (3)

### ISSUE THREAD

**Issue by Pino-Lupin** [ggoffy/wggallery#22]
In reality this feature should not be difficult to implement as it represents a simple feature linked to each image ... as I have already written to you it serves above all for help in finding an image (if we have a "search by ...")
A maximum we need two sub-categories and possible settings ONLY on administration side.
So,  at least, an image could be searched by  : 
- Owner
- Album
- Category
- name
- date
- most liked
- most viewed
- most rated
- best voted
and so on ...

**Comment by ggoffy** [comment]
categories are implemented and ready for testing
