### ISSUE TITLE
Votes (4)

### ISSUE THREAD

**Issue by Pino-Lupin** [ggoffy/wggallery#23]
I suppose you will use the standard Xoops voting system ... I did not check if the date of submission is also in the voting records, if it did not exist it would be good to memorize it; this will help me ( with the categories settings ) to manage voting events such as "contests", "pic of the week", etc ...

A further question that I am asked is: it coild be possible to use numerical votes instead of the evaluation with the classic "stars"? ( i.e. from 1 to 10 )

**Comment by ggoffy** [comment]
implemented. ready for testing
