### ISSUE TITLE
 Error: Class 'XoopsModules/Wggallery/Helper' not found in file /modules/wggallery/include/search.inc.php line 46

### ISSUE THREAD

**Issue by GregMage** [ggoffy/wggallery#28]
A small mistake during a search

**Comment by ggoffy** [comment]
Hi GregMage

I tried to reproduce the error, but it doesn't occur. What have you done exactly?

**Comment by GregMage** [comment]
indeed, I can not reproduce the problem! Can be linked to the module that I coded ...
